dbfilename redis_queue.rdb
dir /home/lux/frappe/erp-bench/config/pids
pidfile /home/lux/frappe/erp-bench/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /home/lux/frappe/erp-bench/config/redis_queue.acl
